[package]
name = "coding-guidelines"
version = "0.1.0"
repository = "https://github.com/sunsided/rust-guidelines"
readme = "guidelines.md"
license = "EUPL-1.2 OR Apache-2.0 OR MIT"
edition = "2024"

[dependencies]
